### ISSUE TITLE
After installation, the ack button is not seen

### ISSUE THREAD

**Issue by kybt** [robusta-dev/kubernetes-chatgpt-bot#13]
error logs:
# kubectl logs robusta-runner-6fc46d9464-w92pg -n robusta
2023-04-03 09:16:08.043 INFO     Importing actions package chatgpt_robusta_actions
2023-04-03 09:16:08.044 INFO     importing actions from chatgpt_robusta_actions.chat_gpt
2023-04-03 09:16:08.048 WARNING  Docstring contains description of token which is not a field on the model
2023-04-03 09:16:08.054 WARNING  Docstring contains description of token which is not a field on the model
2023-04-03 09:16:08.055 INFO     Adding <class 'robusta.core.sinks.robusta.robusta_sink_params.RobustaSinkConfigWrapper'> sink named robusta_ui_sink
2023-04-03 09:16:08.055 ERROR    Error configuring sink robusta_ui_sink of type <class 'robusta.core.sinks.robusta.robusta_sink_params.RobustaSinkConfigWrapper'>: 'utf-8' codec can't decode bytes in position 0-1: invalid continuation byte

**Could you please advise me how to troubleshoot the problem**

**Comment by arikalon1** [comment]
Thanks for reporting it @kybt 
Can you please share your `generated_values.yaml` file?

Please remove any sensitive keys you might have there

**Comment by kybt** [comment]
# cat generated_values.yaml 
clusterName: default
slackApiKey: *********
slackChannel: test
robustaApiKey: ********

playbookRepos:
  chatgpt_robusta_actions:
    url: "https://github.com/robusta-dev/kubernetes-chatgpt-bot.git"

customPlaybooks:
# Add the 'Ask ChatGPT' button to all Prometheus alerts
- triggers:
  - on_prometheus_alert: {}
  actions:
  - chat_gpt_enricher: {}
globalConfig:
  chat_gpt_token: ********

**Comment by kybt** [comment]
# cat generated_values.yaml 
---
clusterName: default
slackApiKey: ***
slackChannel: test
robustaApiKey: ***

playbookRepos:
  chatgpt_robusta_actions:
    url: "https://github.com/robusta-dev/kubernetes-chatgpt-bot.git"

customPlaybooks:
**#** Add the 'Ask ChatGPT' button to all Prometheus alerts
- triggers:
  - on_prometheus_alert: {}
  actions:
  - chat_gpt_enricher: {}
globalConfig:
  chat_gpt_token: "***"
---

**Comment by kybt** [comment]
![image](https://user-images.githubusercontent.com/14269076/229480105-23635944-a82e-4803-977e-e7a5962241f9.png)

**Comment by arikalon1** [comment]
Thanks @kybt 

I'm missing the `sinksConfig` section.

It should be something like:
```
sinksConfig:
- slack_sink:
    name: main_slack_sink
    slack_channel: my-slack-channel
    api_key: xoxb-....
```

You must have a `Slack` sink defined in order to receive the messages in Slack
Did you connect Robusta to Slack?

**Comment by kybt** [comment]
I added the sinksconfig configuration and still can't see the ACK button 😥
generated_values.yamls
![image](https://user-images.githubusercontent.com/14269076/229663286-d3832940-f2ff-42a4-b9ed-b8aaa3122f3d.png)
error log：
![image](https://user-images.githubusercontent.com/14269076/229662948-e5ccd3e3-44e0-4ea4-90e4-0bbe75ad5ae7.png)
![image](https://user-images.githubusercontent.com/14269076/229663596-34cd597c-178c-42c9-85a4-b87cf6d129fa.png)

Is there anything wrong with the generated_values.yamls file format or configuration

**Comment by arikalon1** [comment]
Thanks  @kybt  

The configuration looks good to me 
(no need for the 3 values `slackApiKey`, `slackChannel` and `robustaApiKey`, the `sinksConfig` section is enough)

Robusta has 2 types of notifications:
- Notification based on issues reported by k8s api server (The example above if one of those)
- Notification based on Prometheus alerts

The configuration above adds the Chat GPT button to Prometheus alerts.

You can simulate a Prometheus alerts with the Robusta CLI:
```
robusta playbooks trigger prometheus_alert pod_name=prometheus-robusta-kube-prometheus-st-prometheus-0 pod_namespace=robusta alert_name=KubeContainerWaiting
```

Can you try running that? Do you have a notification for the `KubeContainerWaiting` alert in Slack? 
Does it have the ChatGPT button?

**Comment by kybt** [comment]
I created a CrashLoopBackOff pod that receives prometheus notifcation, but slack doesn't see any notifcation

**Comment by kybt** [comment]
prometheus receives a notifcation, but slack doesn't see any notifcation

**Comment by kybt** [comment]
I suspect it is the sinksConfig configuration, because after I removed the top 3 values slackApiKey, slackChannel and robustaApiKey, No notification could be received, including Notification based on issues reported by k8s api server
![image](https://user-images.githubusercontent.com/14269076/229745310-1b382680-f9b7-40f4-b611-fc306711c363.png)

Also, robusta's pod has consistently had error logs
![image](https://user-images.githubusercontent.com/14269076/229746131-1329379e-229c-42e7-a2c3-f8aab8bcc566.png)

Please help me check again😢

**Comment by arikalon1** [comment]
Hi @kybt 
Can you please comment out the `robustaApiKey` as well?

**Comment by kybt** [comment]
comment out the robustaApiKey，Notification based on issues reported by k8s api server can receive，Still can't see the ASK button
One more question, why is the pod name in the alarm received by the slack k8s api different from the actual pod name in the k8s cluster
the actual pod name in the k8s cluster：
![image](https://user-images.githubusercontent.com/14269076/230249546-298a64f6-f357-45c7-af5c-a66f6be58743.png)
slack pod name：
![image](https://user-images.githubusercontent.com/14269076/230250007-e898d1fc-5a60-493f-8845-c39e3829d129.png)

**Comment by kybt** [comment]
comment out the robustaApiKey，Still can't see the ASK button

**Comment by kybt** [comment]
comment out the robustaApiKey，Notification based on issues reported by k8s api server can't receive，and Still can't see the ASK button

**Comment by kybt** [comment]
Where is the **account_id** generated? Is it a slack username?

**Comment by kybt** [comment]
robusta-runner pod error log
![image](https://user-images.githubusercontent.com/14269076/230261429-7963ba95-2d0b-4236-81da-8a64b3de56ed.png)

**Comment by arikalon1** [comment]
Thanks @kybt 
The account_id is generated when you run `robusta gen-config`

I think the error above indicates a typo in the `generated_values.yaml` file.
Do you use Slack?
If you do, you can join our community Slack [channel](https://bit.ly/robusta-slackhttps://bit.ly/robusta-slack). 
There, we can jump on a quick call, and help you to set it up correctly.

Can you share your `sinksConfig` section ?(without any sensitive keys)

**Comment by kybt** [comment]
sinksConfig as follows:

sinksConfig:
- slack_sink:
name: main_slack_sink
slack_channel: test
api_key: xoxb-****

**Comment by kybt** [comment]
sinksConfig: 
![image](https://user-images.githubusercontent.com/14269076/230306230-14060374-28fa-43e3-9083-63677c68c3da.png)

How to join our community Slack  channel ?

**Comment by kybt** [comment]
After the change to 4 Spaces, the error is no longer reported, but the ASK button is still not visible
![image](https://user-images.githubusercontent.com/14269076/230309940-df3c8784-ccc3-4baa-90c8-e9e25de450f1.png)

**Comment by kybt** [comment]
Users in mainland China don't seem to be able to join 😥
![image](https://user-images.githubusercontent.com/14269076/230311477-a0e67651-6025-462a-8df3-8ded25efbded.png)

**Comment by arikalon1** [comment]
I didn't know that @kybt 

Does this join link works for you?
https://join.slack.com/t/robustacommunity/shared_invite/zt-10rkepc5s-FnXKvGjrBmiTkKdrgDr~wg

**Comment by kybt** [comment]
> I didn't know that @kybt
> 
> Does this join link works for you? https://join.slack.com/t/robustacommunity/shared_invite/zt-10rkepc5s-FnXKvGjrBmiTkKdrgDr~wg

This OK，I have been joined

**Comment by arikalon1** [comment]
@kybt was this resolved?

**Comment by kybt** [comment]
Problem has been solved, thanks!
