### ISSUE TITLE
ChatGPT response is not coming to Slack

### ISSUE THREAD

**Issue by rahulpanwar** [robusta-dev/kubernetes-chatgpt-bot#21]
All of the alerts are coming to slack and Integration also looks good. Ask ChatGPT button is visible in Slack UI
![image](https://github.com/robusta-dev/kubernetes-chatgpt-bot/assets/7690874/a5cd13bc-2ac0-4a25-b865-96588c428a32)
But ChatGPT response is not coming. 

Cluster is behind the Proxy, it may be reason. Any suggestion or ways to debug?

**Comment by arikalon1** [comment]
Hi @rahulpanwar 

Can you please share the logs of the `robusta-runner` pod running in your cluster?

**Comment by rahulpanwar** [comment]
> Hi @rahulpanwar
> 
> Can you please share the logs of the `robusta-runner` pod running in your cluster?

![image](https://github.com/robusta-dev/kubernetes-chatgpt-bot/assets/7690874/0237c5be-3ff4-48e7-be6a-2f10206354dd)

It is running!

**Comment by rahulpanwar** [comment]
Lol, sorry for my ignorance, I checked the logs, My quota is exausted.

`2023-07-07 14:17:37.148 INFO     error_code=None error_message='You exceeded your current quota, please check your plan and billing details.' error_param=None error_type=insufficient_quota message='OpenAI API error received' stream_error=False`

**Comment by rahulpanwar** [comment]
It is working fine after changing API key. 
Thank you for your quick hint @arikalon1

**Comment by aantn** [comment]
Feel free to open a PR showing a warning reply when quota is exhausted!
