### ISSUE TITLE
Not ChatGPT

### ISSUE THREAD

**Issue by dmahlow** [robusta-dev/kubernetes-chatgpt-bot#3]
Correct me if I'm wrong, but this tool is using GPT-3 via the OpenAI API, not the specifically dialog fine tuned, GPT3.5 model based ChatGPT. There is no API into ChatGPT yet and until there is and it's switched over, you might want to adjust the wording in the README and code to avoid confusion.

**Comment by aantn** [comment]
Yep, you're correct. I believe it's using a GPT3.5 model. I'll double check
and update the wording.

**Comment by aantn** [comment]
@dmahlow I've updated the README to try and reduce confusion. It still referrs to ChatGPT, but I hope its more clear.
